version: "3.9"

networks:
  neu_app_net:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neu_api
    restart: unless-stopped
    networks: [neu_app_net]
    ports:
      - "8018:8000"
    environment:
      DB_URL: "neo4j+s://bdfc7297.databases.neo4j.io:7687"
      DB_USER: "bdfc7297"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE: "bdfc7297"          
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_MODEL: "${OPENAI_MODEL}"
      MINIO_ENDPOINT: "${MINIO_ENDPOINT}"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
      MINIO_SECURE: "${MINIO_SECURE}"
      MINIO_BUCKET: "${MINIO_BUCKET}"
      MINIO_BASE_FOLDER: "${MINIO_BASE_FOLDER}"
      MAX_HOPS: "${MAX_HOPS}"
      TOP_K: "${TOP_K}"
      MAX_WORKERS: "${MAX_WORKERS}"